export const products = [
  {
    id: "tee-oversized-black",
    name: "Oversized Tee",
    category: "T-Shirts",
    price: 899,
    rating: 4.6,
    sizes: ["S", "M", "L", "XL"],
    color: "Black",
    blurb: "Soft cotton, relaxed drape, everyday staple.",
    image: "https://source.unsplash.com/600x800/?black,tshirt,fashion",
  },
  {
    id: "tee-ribbed-white",
    name: "Ribbed Slim Tee",
    category: "T-Shirts",
    price: 799,
    rating: 4.4,
    sizes: ["XS", "S", "M", "L"],
    color: "White",
    blurb: "Clean fit with rib texture - easy to layer.",
    image: "https://source.unsplash.com/600x800/?white,tshirt,women,fashion",
  },
  {
    id: "shirt-oxford-blue",
    name: "Oxford Shirt",
    category: "Shirts",
    price: 1599,
    rating: 4.7,
    sizes: ["S", "M", "L", "XL"],
    color: "Blue",
    blurb: "Crisp collar, breathable weave, office-to-weekend.",
    image: "https://source.unsplash.com/600x800/?oxford,shirt,men",
  },
  {
    id: "shirt-linen-sand",
    name: "Linen Shirt",
    category: "Shirts",
    price: 1799,
    rating: 4.5,
    sizes: ["S", "M", "L", "XL"],
    color: "Sand",
    blurb: "Lightweight linen - made for warm days.",
    image: "https://source.unsplash.com/600x800/?linen,shirt,fashion",
  },
  {
    id: "jeans-straight-indigo",
    name: "Straight Jeans",
    category: "Jeans",
    price: 2199,
    rating: 4.6,
    sizes: ["S", "M", "L", "XL"],
    color: "Indigo",
    blurb: "Classic straight leg with premium stretch denim.",
    image: "https://source.unsplash.com/600x800/?denim,jeans,indigo",
  },
  {
    id: "jeans-relaxed-washed",
    name: "Relaxed Jeans",
    category: "Jeans",
    price: 2399,
    rating: 4.3,
    sizes: ["S", "M", "L", "XL"],
    color: "Washed Blue",
    blurb: "Roomy through the thigh for all-day comfort.",
    image: "https://source.unsplash.com/600x800/?relaxed,jeans,fashion",
  },
  {
    id: "hoodie-fleece-graphite",
    name: "Fleece Hoodie",
    category: "Hoodies",
    price: 1999,
    rating: 4.8,
    sizes: ["S", "M", "L", "XL"],
    color: "Graphite",
    blurb: "Thick fleece, warm hood, minimal branding.",
    image: "https://source.unsplash.com/600x800/?hoodie,fleece",
  },
  {
    id: "hoodie-zip-olive",
    name: "Zip Hoodie",
    category: "Hoodies",
    price: 2099,
    rating: 4.4,
    sizes: ["XS", "S", "M", "L", "XL"],
    color: "Olive",
    blurb: "Easy zip-up layer with clean seams.",
    image: "https://source.unsplash.com/600x800/?zip,hoodie,olive",
  },
  {
    id: "jacket-bomber-forest",
    name: "Bomber Jacket",
    category: "Jackets",
    price: 3299,
    rating: 4.7,
    sizes: ["S", "M", "L", "XL"],
    color: "Forest",
    blurb: "Structured bomber with a smooth matte finish.",
    image: "https://source.unsplash.com/600x800/?bomber,jacket",
  },
  {
    id: "jacket-denim-mid",
    name: "Denim Jacket",
    category: "Jackets",
    price: 2999,
    rating: 4.5,
    sizes: ["S", "M", "L", "XL"],
    color: "Mid Blue",
    blurb: "Iconic denim layer - works with everything.",
    image: "https://source.unsplash.com/600x800/?denim,jacket",
  },
  {
    id: "dress-midi-berry",
    name: "Midi Dress",
    category: "Dresses",
    price: 2799,
    rating: 4.6,
    sizes: ["XS", "S", "M", "L"],
    color: "Berry",
    blurb: "Flowy silhouette with a flattering waist tie.",
    image: "https://source.unsplash.com/600x800/?midi,dress,fashion",
  },
  {
    id: "dress-shirt-black",
    name: "Shirt Dress",
    category: "Dresses",
    price: 2599,
    rating: 4.3,
    sizes: ["XS", "S", "M", "L", "XL"],
    color: "Black",
    blurb: "Button-down dress with crisp structure.",
    image: "https://source.unsplash.com/600x800/?shirt,dress,black",
  },
  {
    id: "grocery-rice-5kg",
    name: "Premium Rice (5kg)",
    category: "Groceries",
    price: 599,
    rating: 4.5,
    sizes: ["Std"],
    color: "Pack",
    blurb: "Daily-use long grain rice for home cooking.",
    image: "https://source.unsplash.com/600x800/?rice,groceries",
  },
  {
    id: "grocery-wheat-flour",
    name: "Whole Wheat Flour (10kg)",
    category: "Groceries",
    price: 649,
    rating: 4.4,
    sizes: ["Std"],
    color: "Pack",
    blurb: "Stone-ground atta for soft rotis and chapatis.",
    image: "https://source.unsplash.com/600x800/?wheat,flour,grocery",
  },
  {
    id: "grocery-cooking-oil",
    name: "Sunflower Oil (5L)",
    category: "Groceries",
    price: 899,
    rating: 4.3,
    sizes: ["Std"],
    color: "Bottle",
    blurb: "Refined sunflower oil with light taste.",
    image: "https://source.unsplash.com/600x800/?sunflower,oil,bottle",
  },
  {
    id: "grocery-milk-pack",
    name: "Milk Pack (1L)",
    category: "Groceries",
    price: 64,
    rating: 4.6,
    sizes: ["Std"],
    color: "Dairy",
    blurb: "Fresh toned milk for daily use.",
    image: "https://source.unsplash.com/600x800/?milk,packet,dairy",
  },
  {
    id: "elect-phone-aura-x",
    name: "Aura X Smartphone",
    category: "Electronics",
    price: 18999,
    rating: 4.5,
    sizes: ["Std"],
    color: "Midnight",
    blurb: "6.5 inch display, fast charging, dual camera.",
    image: "https://source.unsplash.com/600x800/?smartphone,mobile",
  },
  {
    id: "elect-buds-sonic",
    name: "Sonic Wireless Earbuds",
    category: "Electronics",
    price: 2499,
    rating: 4.4,
    sizes: ["Std"],
    color: "Black",
    blurb: "Low-latency audio with compact charging case.",
    image: "https://source.unsplash.com/600x800/?wireless,earbuds",
  },
  {
    id: "elect-watch-pulse",
    name: "Pulse Smartwatch",
    category: "Electronics",
    price: 3299,
    rating: 4.2,
    sizes: ["Std"],
    color: "Graphite",
    blurb: "Track steps, heart rate, and notifications.",
    image: "https://source.unsplash.com/600x800/?smartwatch",
  },
  {
    id: "elect-speaker-mini",
    name: "Mini Bluetooth Speaker",
    category: "Electronics",
    price: 1599,
    rating: 4.3,
    sizes: ["Std"],
    color: "Blue",
    blurb: "Portable speaker with clear bass and 10h battery.",
    image: "https://source.unsplash.com/600x800/?bluetooth,speaker",
  },
];

export const categories = Array.from(new Set(products.map((p) => p.category))).sort();
